### ISSUE TITLE
Edit map

### ISSUE THREAD

**Issue by TeslaWorks239** [kebasyaty/django-editor-ymaps#6]
После нажатия  "Редактировать карту" загружается белая пустая страница. В консоли выскакивают 2 ошибки. Failed to load module script: The server chunk_vendors.f5273d59.js:1 Failed to load module script: The server 

Failed to load module script: The server app563834c7.js:1 non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
Как можно это исправить?

**Comment by kebasyaty** [comment]
Здравствуйте!
С проблемой `JavaScript MIME type` я не сталкивался, в текущей проверке
такой оишибки тоже нет.

На эту тему ести вот такие ссылки, возможно Вам это как-то поможет:
https://github.com/novnc/noVNC/issues/949
https://stackoverflow.com/questions/46138375/trouble-with-es6-modules

пн, 27 апр. 2020 г. в 21:49, TeslaWorks239 <notifications@github.com>:

**Comment by TeslaWorks239** [comment]
Статьи помогли, большое спасибо. Хотелось бы еще уточнить, есть ли возможность отрисовки точке или траекторий из json файлов напрямую через view?

**Comment by kebasyaty** [comment]
Если я правильно понял, вам нужно загружать геообъекты на карту из
собственных json файлов.
Такой вариант не предусмотрен, для этого потребуется  кастомизировать
проект в той части которая отвечает за загрузку геообъектов. К тому же,
Ваши json файлы должны будут соответствовать определенной структуре для
каждого типа геообъектов.

вт, 28 апр. 2020 г. в 15:15, TeslaWorks239 <notifications@github.com>:

**Comment by TeslaWorks239** [comment]
Хорошо, спасибо

**Comment by TeslaWorks239** [comment]
При работе с моделями напрямую возникла проблема, что поля category в Placemark, Polyline, Polygon связаны через ForeignKey(CategoryPlacemark, .....) , поэтому при создании отдельно Polyline.objects.create или Polygon.objects.create и передачи туда параметра CategoryPolyline и CategoryPolygon соответственно, возникает ошибка: Cannot assign "<CategoryPolygon: Коронавирус>": "Polygon.category" must be a "CategoryPlacemark" instance. Возможно при добавлении параметров blank=True, null=True в  ForeignKey ошибка исчезнет. Сможете помочь?

**Comment by kebasyaty** [comment]
Добавить blank=True, null=True для категорий недопустимо, категории должны
быть обязательными (blank=False) для нормальной работы редактора.

Попробуйте подойти к решению проблемы через формы.
===
from djeym.forms import PlacemarkForm, PolylineForm, PolygonForm

form = PlacemarkForm(request.POST)
if form.is_valid():
    placemark = form.save()
// OR
form = PolylineForm(request.POST)
if form.is_valid():
    polyline = form.save()
// OR
form = PolygonForm(request.POST)
if form.is_valid():
    polygon = form.save()
===

ср, 29 апр. 2020 г. в 01:20, TeslaWorks239 <notifications@github.com>:
