### ISSUE TITLE
Форма

### ISSUE THREAD

**Issue by Ignor-GTO** [kebasyaty/django-editor-ymaps#65]
Добрый день хочу заменить иконки на текст но не как не могу найти где этот блок кода в проекте.
![image](https://github.com/user-attachments/assets/1aed12af-752b-4f8b-8c3f-9c77d2f1a131)

И сделать всё в одной форме category subcategories header body footer
![image](https://github.com/user-attachments/assets/8b33262c-8762-4f3d-aa1f-3275445ee751)

Если не сложно подскажите пожалуйста.

**Comment by kebasyaty** [comment]
Привет!

Чтобы изменить иконки:
1) Клонируй свой GitHub репозиторий django-editor-ymaps.
2) Зайди в раздел django-editor-ymaps/nodymaps/editor и выполни npm i
   (этот проект на Node.js,  Vue.js и Vuetify 2)
3) Открой файл django-editor-ymaps/nodymaps/editor/src/components/DialogCreate.vue
  Замени название иконок на свои названия:
  data: () => ({
    icons: ["mdi-map-marker", "mdi-routes", "mdi-beach", "mdi-fire"],
  }),
  Настрой вот эту кнопку (она в самом верху):
  (Настройки для кнопки: https://v2.vuetifyjs.com/en/components/buttons/)
  <v-btn
    v-for="(icon, index) in icons"
    :key="`action-btn-${index}`"
    small
    fab
    depressed
    class="mx-1"
    :disabled="index === 3 ? !controlsHeatmap.panel1.isActive : false"
    :color="colorControlsTheme"
    @click="createGeoObject(index)"
  >
    <v-icon :color="colorButtonsTextTheme">{{ icons[index] }}</v-icon>
  </v-btn>
4) Сделай билд: npm run build
5) Перемести скрипты и стили в раздел django-editor-ymaps/djeym/static/djeym/nodymaps/editor


И сделать всё в одной форме category subcategories header body footer:
Это и так все в одном месте, или я неправильно понял вопрос.

P.S.
Будут вопросы обращайся:
kebasyaty@gmail.com
